name: singelton_dars
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  hive: ^2.2.3
  shared_preferences: ^2.2.2
  hive_flutter: any
  path_provider: ^2.1.2
  objectbox_flutter_libs: ^2.4.0
  objectbox: ^2.4.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  pinput: ^3.0.1
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  open_file: ^3.3.2
  share_plus: ^7.2.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: any 
  build_runner: any
  objectbox_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets: 
    - assets/icon/login/
    - assets/icon/profile/
    - assets/images/
